In [24]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings('ignore')

In [25]:
df=pd.read_csv('tmdb_5000_movies.csv')

In [26]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [27]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [28]:
df1=pd.read_csv('tmdb_5000_credits.csv')

In [29]:
df1.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [31]:
df.shape

(4803, 20)

In [32]:
df1.shape

(4803, 4)

In [33]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df=df.drop_duplicates().reset_index(drop=True)

In [36]:
df.duplicated().sum()

np.int64(0)

In [40]:
# Now select the columns you want

# FIRST - Load your data into a DataFrame

df = pd.read_csv('tmdb_5000_movies.csv')  # or whatever your file is called

# NOW you can select columns
df = df[['title', 'overview', 'genres', 'vote_average', 'tagline','popularity']]


print(df.head())

                                      title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

                                              genres  vote_average  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1

                                          tagline  popularity
0                     Enter the World of Pandora.  150.437577
1  At the end of the world, the adventure begins.  139.082615
2                           A Plan No One Escapes  107.376788
3                                 The Legend Ends  112.312950
4            Lost in our world, found in another.   43.926995

In [39]:
df

,title,overview,genres,vote_average,popularity
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",7.2,150.437577
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",6.9,139.082615
2,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.3,107.376788
3,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",7.6,112.312950
4,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.1,43.926995
...,...,...,...,...,...
4798,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",6.6,14.269792
4799,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",5.9,0.642552
4800,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",7.0,1.444476
4801,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],5.7,0.857008
4802,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]",6.3,1.929883

In [41]:
df.isnull().sum()

title             0
overview          3
genres            0
vote_average      0
tagline         844
popularity        0
dtype: int64

In [42]:
df=df.dropna(subset=['title'])

In [43]:
#filling null with empty space
df['overview']=df['overview'].fillna(' ')

In [44]:
df.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [49]:
import ast
df['genres']=df['genres'].apply(lambda x: " ".join([i['name']for i in ast.literal_eval(x)]) )

In [50]:
df.head()

,title,overview,genres,vote_average,tagline,popularity
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,7.2,Enter the World of Pandora.,150.437577
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,6.9,"At the end of the world, the adventure begins.",139.082615
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,6.3,A Plan No One Escapes,107.376788
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,7.6,The Legend Ends,112.312950
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,6.1,"Lost in our world, found in another.",43.926995

In [51]:
#filling null with empty space
df['tagline']=df['tagline'].fillna(' ')

In [52]:
df['tags']=df['overview']+ " "+ df["genres"]+" " +df['tagline']

In [53]:
df.head()

,title,overview,genres,vote_average,tagline,popularity,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,7.2,Enter the World of Pandora.,150.437577,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,6.9,"At the end of the world, the adventure begins.",139.082615,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,6.3,A Plan No One Escapes,107.376788,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,7.6,The Legend Ends,112.312950,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,6.1,"Lost in our world, found in another.",43.926995,"John Carter is a war-weary, former military ca..."

In [56]:
df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction Enter the World of Pandora.'

In [57]:

df['tags'][1]

'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. Adventure Fantasy Action At the end of the world, the adventure begins.'

In [59]:
#moving to nlp processing 
import nltk 
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [60]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...

True

In [74]:
stop_words=set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [80]:
def preprocess_text(text):
    # Convert to lowercase
    text = str(text).lower()
    
    # Remove punctuation (keep only letters, numbers, and spaces)
    text = re.sub(r'[^\w\s]', ' ', text)
    
    # Split into words
    words = text.split()
    
    # Remove stopwords
    words = [word for word in words if word not in stop_words]  # Fixed: 'word' not 'words'
    
    # Lemmatize
    words = [lemmatizer.lemmatize(word) for word in words]
    
    return " ".join(words)

In [81]:

df['tags'] = df['tags'].apply(preprocess_text)

In [82]:
df['tags'][0]

'22nd century paraplegic marine dispatched moon pandora unique mission becomes torn following order protecting alien civilization action adventure fantasy science fiction enter world pandora'

In [83]:
df=df.reset_index(drop=True)

In [89]:

indices = pd.Series(df.index, index=df['title']).drop_duplicates() 
indices

title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [108]:
#convert it into vector 
#apply the vectorization 
from sklearn.feature_extraction.text import TfidfVectorizer

In [109]:
tfidf=TfidfVectorizer(max_features=50000,ngram_range=(1, 2),stop_words='english')

In [110]:
tfidf_matrix=tfidf.fit_transform(df['tags'])

In [111]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 204575 stored elements and shape (4803, 50000)>

In [ ]:
#cosine similarity to predicting the movies

In [112]:
from sklearn.metrics.pairwise import cosine_similarity

In [117]:
def recommend(title, n=10):
    if title not in indices:
      return ['Movie not found']
    idx= indices[title]
    sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx=sim_score.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx]

In [119]:
recommend('Toy Story')

343                                           Toy Story 2
42                                            Toy Story 3
1779                               The 40 Year Old Virgin
891                                       Man on the Moon
3379                                         Factory Girl
2869                               For Your Consideration
837                                            Free Birds
3873                                        Class of 1984
3065                                           Heartbeeps
4279    The 41–Year–Old Virgin Who Knocked Up Sarah Ma...
Name: title, dtype: object

In [120]:
recommend('Avatar',4)

1341                          The Inhabited Island
634                                     The Matrix
369     Lara Croft Tomb Raider: The Cradle of Life
3604                                     Apollo 18
Name: title, dtype: object

In [123]:
import pickle 
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(df,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))